#!/bin/sh

source `dirname $0`/build-init build.it

TREE_ISH="$1"
TREE_ISH=${TREE_ISH:=HEAD}

STATUS=$(git archive --format=zip $TREE_ISH |\
    curl -s -o /dev/null -w '%{http_code}\n' -F 'name=zip' -F 'file0=@-' -F 'json={parameter:{name:"zip",file:"file0"}}' "$BUILD_URL")

if [ '302' = "$STATUS" ]; then
    echo "Build started."
else
    echo "Error [$STATUS]"
fi